CONTIKI_PROJECT = node
PROJECT_SOURCEFILES = broadcast-message.c routing-table.c routing-message.c data-message.c option-message.c
all: $(CONTIKI_PROJECT) 

#UIP_CONF_IPV6=1

CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
