CONTIKI_PROJECT = node
PROJECT_SOURCEFILES = discovery-message.c maintenance-message.c route-message.c managment-message.c data-message.c routing-table.c
all: $(CONTIKI_PROJECT) 

#UIP_CONF_IPV6=1

CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
