CONTIKI_PROJECT = root
PROJECT_SOURCEFILES = discovery-message.c maintenance-message.c sensor-message.c routing-table.c
all: $(CONTIKI_PROJECT) 

#UIP_CONF_IPV6=1

CONTIKI = ../../../contiki
include $(CONTIKI)/Makefile.include
